### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Bismarck-GM**
## Milestone 1:

- Add React-Test-Library ('@testing-library/react') dependency.
- Add tests for Logic.
- Add tests for Components.

I'm not sure if the tests for components are ok being that few. I'm not going to use snapshots, just RTL. I'll really like feedback about those that I made for Button and Quote.

Thanks for the review 🌵

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Bismarck-GM, great job on this project :100: The README is professional, the PR has a title and a short description :fireworks: The commit messages are readable and easy to understand :1st_place_medal: Most of the functionality of the app is tested :+1: 

However, there is one requirement let out that we need to fix before proceeding, Kindly check the comment below:
- There are snapshot tests that are checking if all elements from Math Magicians mockups are displayed, currently, we are missing this test, let us implement it

Once this is resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Bismarck-GM** [comment]
Hello, Daniel @addod19 . 
Please read the PR message before copy-pasting the Rubric bullet-points.

I'm not using Snapshots, I'm using RTL for testing components, it was in the guides and I want to see if what I've done with those is fine or if there's something else that I'm missing.

Thanks.

**Comment by addod19** [comment]
> ## Status: Require changes  
> Hi @Bismarck-GM, great job on this project  The README is professional, the PR has a title and a short description  The commit messages are readable and easy to understand  Most of the functionality of the app is tested 
> 
> However, there is one requirement let out that we need to fix before proceeding, Kindly check the comment below:
> 
> * There are snapshot tests that are checking if all elements from Math Magicians mockups are displayed, currently, we are missing this test, let us implement it
> 
> Once this is resolved, kindly submit another code review request 
> _Happy coding_ 
> [Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

re

**Comment by Bismarck-GM** [comment]
Hello again, Daniel. You're doing exactly the thing I kindly asked not to do.
I'm trying to learn and it seems you're mocking me.

- Snapshots are not required in the project guidelines. ◀️
- You can test mock-up text, etc without using Snapshots.
- One of the purposes of using RTL is to not use Snapshots.

If you don't know how to test without Snapshots, please just say so and I can ask somewhere else.

**Comment by addod19** [comment]
> Hello again, Daniel. You're doing exactly the thing I kindly asked not to do.
> I'm trying to learn and it seems you're mocking me.
> 
> * Snapshots are not required in the project guidelines. arrow_backward
> * You can test mock-up text, etc without using Snapshots.
> * One of the purposes of using RTL is to not use Snapshots.
> 
> If you don't know how to test without Snapshots, please just say so and I can ask somewhere else.

Hi @Bismarck-GM, yeah I made a mistake ignoring your creativity by not using snapshot test to test for components but rather use RTL instead. What I should have said was to ask you to add a test for the "home" component and the "calculator" component although you have tested for the "quote" component and added a button test, that is cool :+1: 
Kindly implement a test for the home and calculator component as in the screenshot
testing

Did I miss anything?
Any feedback is welcome!!!

**Comment by Bismarck-GM** [comment]
Hello @addod19. Thanks for coming back and correcting the request.

Yes, I'll add the missing tests for the components now that you confirmed the two I did (quote and button) are actually fine.

Thanks again 🌵 .

**Comment by Bismarck-GM** [comment]
## Milestone 2:

### Add missing tests.

- Understood well how to tests with RTL using the `screen` variable. It's easier than using Snapshots and more reliable than them if the project is going to grow.

- The parent `Calculator.js` component is the one that tests the functionality and displays of the Application. `Button.js` test checks for functions being call when pressed. Both other tests just check mock-up text is present.

Thanks for the review 🐴

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job @Bismarck-GM :clap: :clap: :100: :+1:, and thanks for making the required changes :hammer: :wrench:.

Now you can merge, your project is approved :checkered_flag: 

## Happy Coding :tophat:

**Pull request merged**
